### ISSUE TITLE
Any issues with the preview?

### ISSUE THREAD

**Issue by MindTooth** [mattermost/mattermost-docker-preview#2]
Hi,

Been trying the last few days to run the preview.  But it won't reply when accessing the URL.

What steps can I take to check if it's running inside the container and is accessible.

When I attach the shell, I get some errors.
I'll try posting them later.  (The disadvantage of using a different platform at work than 1Password and a giant random password for Github :-P)

Ed1t: https://gist.github.com/MindTooth/c0334c4e655db60c23740b61350d3032

**Comment by ThajASara** [comment]
I am having a similar issue.  Not getting anything when visiting the URL.

**Comment by joelnb** [comment]
Could you please test with this [pull request](https://github.com/mattermost/mattermost-docker-preview/pull/5) added and see if it fixes the issue for you? If you're unsure how to do that you can run:

```
git clone https://github.com/joelnb/mattermost-docker-preview.git
cd mattermost-docker-preview
git checkout wait-until-mysql-really-ready
docker build -t joelnb/mattermost .
docker run --name mattermost-preview -d --publish 8065:8065 joelnb/mattermost
```

You can also test it by simply running:

```
docker run --name mattermost-preview -d --publish 8065:8065 joelnb/mattermost
```

As the image is pushed to docker hub. I'm not sure if you will be okay doing this though as that way you are unable to verify the included changes.

**Comment by ThajASara** [comment]
I tried the pull request and was still unable to access from the URL.

**Comment by joelnb** [comment]
Can you post the output of 'docker logs' when you do so? Also are you
accessing via localhost:8065 or 127.0.0.1:8065? I've found it works better
using the IP even though I'm not sure why that would be the case.

**Comment by MindTooth** [comment]
The PR worked for me.  Thanks 😊

**Comment by ThajASara** [comment]
I reran it using the 127.0.0.1 ip address and it did work.  Unfortunately, since I am using a dynamic DNS to make the container public facing I'm not sure how I can make that work.

**Comment by ThajASara** [comment]
I'm sorry I stand corrected.  The new pull did work correctly.  Sorry for the confusion.  Thanks for the work!

**Comment by joelnb** [comment]
Awesome, glad to be of assistance. Hopefully someone can get the pull request merged and update the docker hub image.
