### ISSUE TITLE
Make mysql startup optional

### ISSUE THREAD

**Issue by travisghansen** [mattermost/mattermost-docker-preview#20]
Any chance you could add an environment variable to make the mysql startup optional?

**Comment by jasonblais** [comment]
Thanks @travisghansen, can you help file issues in our platform repo instead, following these guidelines: https://www.mattermost.org/filing-issues/

**Comment by travisghansen** [comment]
Would it be easier if I just submit a MR?

**Comment by jasonblais** [comment]
If you're interested to submit a PR, we'd be happy to review it :)

**Comment by travisghansen** [comment]
Added MR #21

**Comment by jasonblais** [comment]
Thanks @travisghansen!

**Comment by travisghansen** [comment]
Any chance we can get this pulled in before the new images hit?
