### ISSUE TITLE
A docker "dev" preview would be nice.

### ISSUE THREAD

**Issue by dracwyrm** [mattermost/mattermost-docker-preview#3]
Is there a way to have a docker file that pulls in the latest code from https://github.com/mattermost/platform and build the preview image? This would give a chance to test the latest code with before releases to see how things will change. Loaded with a bunch of the preview posts and users would give a good feel of the changes and explore it fully before live systems. This could make updating the systems quicker as the changes will be familiar in advance.

This what "Preview Image" means to me. :)

Thanks.

**Comment by crspeller** [comment]
@dracwyrm We did have an image like that before. However people where confusing it with a production images witch was causing a bunch of unnecessary support work. So we decided to remove it. 

Your welcome to create an unofficial one. The link for the latest master build is: https://releases.mattermost.com/mattermost-platform/master/mattermost-team-linux-amd64.tar.gz
