### ISSUE TITLE
Upgrade to mattermost 5.0.0

### ISSUE THREAD

**Issue by 3kami3** [mattermost/mattermost-docker-preview#32]
Upgrade to mattermost 5.0.0 indicated an error.
```
mattermost_1 | ------------------------------------ ERROR ------------------------------------------------
mattermost_1 | The platform binary has been deprecated, please switch to using the new mattermost binary.
mattermost_1 | The platform binary will be removed in a future version.
mattermost_1 | -------------------------------------------------------------------------------------------
```

**Comment by smccannmc2** [comment]
Workaround/Fix Below:

Before Upgrade:
[Unit]
Description=Mattermost
After=syslog.target network.target postgresql-9.4.service

[Service]
Type=notify
WorkingDirectory=/opt/mattermost
User=mattermost
ExecStart=/opt/mattermost/bin/platform
PIDFile=/var/spool/mattermost/pid/master.pid
TimeoutStartSec=3600
LimitNOFILE=49152

[Install]
WantedBy=multi-user.target

After Upgrade:

[Unit]
Description=Mattermost
After=syslog.target network.target postgresql-9.4.service

[Service]
Type=notify
WorkingDirectory=/opt/mattermost
User=mattermost
ExecStart=/opt/mattermost/bin/mattermost
PIDFile=/var/spool/mattermost/pid/master.pid
TimeoutStartSec=3600
LimitNOFILE=49152

[Install]
WantedBy=multi-user.target

**Comment by cpanato** [comment]
this is fixed. closing

**Comment by biva** [comment]
Hello,
I still see this message on 5.7.1

**Comment by hassanshamshir** [comment]
------------------------------------ ERROR ------------------------------------------------
The platform binary has been deprecated, please switch to using the new mattermost binary.
The platform binary will be removed in a future version.
-------------------------------------------------------------------------------------------
	
{"level":"info","ts":1560507946.2110686,"caller":"utils/i18n.go:78","msg":"Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'"}
{"level":"info","ts":1560507946.21118,"caller":"app/app.go:204","msg":"Server is initializing..."}
{"level":"info","ts":1560507946.213615,"caller":"sqlstore/supplier.go:209","msg":"Pinging SQL master database"}
{"level":"error","ts":1560507946.213869,"caller":"sqlstore/supplier.go:221","msg":"Failed to ping DB retrying in 10 seconds err=dial tcp: lookup <host-name-or-IP>: no such host"}

**Comment by hassanshamshir** [comment]
Plz help me

**Comment by cpanato** [comment]
@hassanshamshir which image are you using?

**Comment by hassanshamshir** [comment]
I am not using any docker image.

**Comment by hassanshamshir** [comment]
I fallow the instruction from Mattermost Documentation.

**Comment by hassanshamshir** [comment]
https://jeffschering.github.io/mmdocs/upgrade/install/install-ubuntu-1604.html#installing-ubuntu-server-16-04-lts

**Comment by hassanshamshir** [comment]
Now I resolve the previous error and stuck in the next one.

**Comment by hassanshamshir** [comment]
Error: listen tcp :8065: bind: address already in use

**Comment by 3kami3** [comment]
@hassanshamshir  
If you are not using a Docker image, you should report issues to [mattermost-server](https://github.com/mattermost/mattermost-server/issues) instead.  
This issue reports about Docker image of mattermost-docker-preview.

**Comment by jijocdmx** [comment]
> Workaround/Fix Below:
> 
> Before Upgrade:
> [Unit]
> Description=Mattermost
> After=syslog.target network.target postgresql-9.4.service
> 
> [Service]
> Type=notify
> WorkingDirectory=/opt/mattermost
> User=mattermost
> ExecStart=/opt/mattermost/bin/platform
> PIDFile=/var/spool/mattermost/pid/master.pid
> TimeoutStartSec=3600
> LimitNOFILE=49152
> 
> [Install]
> WantedBy=multi-user.target
> 
> After Upgrade:
> 
> [Unit]
> Description=Mattermost
> After=syslog.target network.target postgresql-9.4.service
> 
> [Service]
> Type=notify
> WorkingDirectory=/opt/mattermost
> User=mattermost
> ExecStart=/opt/mattermost/bin/mattermost
> PIDFile=/var/spool/mattermost/pid/master.pid
> TimeoutStartSec=3600
> LimitNOFILE=49152
> 
> [Install]
> WantedBy=multi-user.target

Already using 5.2 but suddenly this error started appearing yesterday. Also in docker, which service file has to be edited?
