### ISSUE TITLE
Consider setting EnableOpenServer to true by default

### ISSUE THREAD

**Issue by Autre31415** [mattermost/mattermost-docker-preview#41]
~~After starting up this preview image for the first time via the one-liner documented here I'm trapped at the sign in page. There's no default user account documented, and I'm not given the option to generate the initial admin account.~~

EDIT:

After investigating this further I was able to proceed by editing the config file like so:

First:
```
docker exec -ti mattermost-preview /bin/bash
apt install vim
vim mattermost/config/docker_config.json
```

Then:

Set `EnableOpenServer` to `true`

```
docker restart mattermost-preview
```

After that I was able to generate myself an account.

Since this is designed to be a quick preview of mattermost I think it would be a good idea if that setting was turned on by default so that it's quicker to dive into

**Comment by joelnb** [comment]
I think you have some other issue and that setting `EnableOpenServer` is not necessarily the answer. When I run the command from the README and then go to `localhost:8065` I get redirected to http://localhost:8065/signup_email and see this page:

![2019-01-03-10-07-27](https://user-images.githubusercontent.com/6627979/50632431-bb39e280-0f3f-11e9-8f2f-98e0ce548764.png)

If that's not happening for you you should probably check `docker logs mattermost-preview` to see if you can work out the reason why.

**Comment by cpanato** [comment]
closing, no issues here. this image is just to try out should not be used for production
