### ISSUE TITLE
version 5.2.1 - Error in Docker log  - Binary Deprecated

### ISSUE THREAD

**Issue by jijocdmx** [mattermost/mattermost-docker-preview#44]
**Mattermost Version: 5.2.1
Database Schema Version: 5.2.0
Database: mysql**

Getting the below error.

==

------------------------------------ ERROR ------------------------------------------------

The platform binary has been deprecated, please switch to using the new mattermost binary.

The platform binary will be removed in a future version.

-------------------------------------------------------------------------------------------

	

{"level":"error","ts":1565703136.6825554,"caller":"commands/server.go:74","msg":"The platform binary has been deprecated, please switch to using the mattermost binary."}

{"level":"error","ts":1565703137.3925903,"caller":"plugin/client_rpc.go:154","msg":"RPC call to OnActivate plugin failed.","plugin_id":"zoom","error":"reading body EOF"}

{"level":"error","ts":1565703137.4114516,"caller":"plugin/client_rpc_generated.go:66","msg":"RPC call OnConfigurationChange to plugin failed.","plugin_id":"zoom","error":"connection is shut down"}

{"level":"error","ts":1565703137.4423308,"caller":"plugin/client_rpc_generated.go:66","msg":"RPC call OnConfigurationChange to plugin failed.","plugin_id":"zoom","error":"connection is shut down"}
==
Could anyone help?

**Comment by cpanato** [comment]
this is fixed in newer images

**Comment by jijocdmx** [comment]
Thank you! The issue was different and this one seems a warning not causing
any problems. We have already fixed the issue we were facing.
*Jijo* | *Sr. Server Administrator*
*CodeMax IT Solutions Pvt. Ltd.*
Email jijo.joy@CdMx.in
*Address *A-201/202, 2nd Floor, Asian Costa Pinnacle,
Behind Hotel Surya Palace, Fatorda, Margao, Goa (403602)
Mobile +91 9567224788 Website CdMx.in <https://cdmx.in/>
