### ISSUE TITLE
Wrong tar-file in line 21 in Dockerfile (?)

### ISSUE THREAD

**Issue by phsteffen** [mattermost/mattermost-docker-preview#6]
Hi Folks,

there is perhaps a wrong tar-File in Line 21 in the Dockerfile.

Line 21:
`RUN tar -zxvf ./mattermost-team-3.2.0-linux.amd64.tar.gz`

it should be (?):
`RUN tar -zxvf ./mattermost-team-3.2.0-linux-amd64.tar.gz`

instead of "." an "-"

best regards
  Philip

**Comment by crspeller** [comment]
Fixed by https://github.com/mattermost/mattermost-docker-preview/pull/7
