### ISSUE TITLE
Unable to create initial System Admin account on new container

### ISSUE THREAD

**Issue by matthew-src** [mattermost/mattermost-docker-preview#90]
After updating to the latest docker preview image, and running a new container, selecting "Don't have an account?" on the login page does not allow the user to create a new System Admin account. Instead, it links to `http://localhost:8065/access_problem`, and instructs the user to contact the workspace admin.

**Comment by Asubayo** [comment]
I have the same issue. What is the workaround ? How can we install a previous release ?

**Comment by matthew-src** [comment]
This issue has been resolved.
